### ISSUE TITLE
"Selfaware Komponente"

### ISSUE THREAD

**Issue by ratnim** [ratnim/SelfawareMonopoly#7]
Selfaware Komponente soll das hinterliegende übergriffige System beschreiben.

Was soll die übergriffige Komponente können und wie soll sie in das normale Spiel involviert werden?

Welche Technologien sollen wir nutzen und wie können wir diese Komponente auf das Spiel zugreifen lassen?

**Comment by Highlife1911** [comment]
Implement the Project in C++ using a client-server architecture.

##Server##
The server will be implemented using C++ and Qt. It serves as a state machine and listens to HTTP requests to modify or query the state. The requests are following the REST model and the interchange data format is json. This is a console application that implements the rules of the game.

##Client##
The client will be implemented in C++ and Qt. At startup the user must enter a server ip in order to play a game. After that it queries constantly the current state from the server. The state is then visualized using OpenGL or the Qt software renderer. On the users turn the client visualizes the actions it can take. Taking a action results in a query that is sent to the server to modify its state.

##Data transfer##
Using plain text REST as a transfer standard allows to easily debug the connection. The advantage of keeping the connection asynchon is that it simplifies its implementation because of the abstraction from low level data transfers. In contrast it is not the most efficient way of transporting data.

###Coding Style###
The most up to date version of the C++ language that is aviable on all mayor platforms should be used. The used compilers should include Visual Studio 2017 15.6 and clang5 and the program should work on Windows and Linux using CMake. Every change must be commited on a seperate branch which will be reviewed by multiple people when merging into the master.

###Why QT?###
It contains platform independent abstractions for network, filesystem, databases, user interface and opengl.

**Comment by ratnim** [comment]
@Highlife1911  kannst du den Beitrag in #10 verschieben? Der Inhalt dieses Tickets zielt eher auf die Übergriffige Systemkomponente ab und wo und wie sie integriert wird.

**Comment by ratnim** [comment]
I think its important that the System offers you the cheats, just in some by the system choosen points in the game. To realy force the player to take them.

**Comment by ratnim** [comment]
May you can rebuy your ingame stuff for extern information resources.

**Comment by Highlife1911** [comment]
Allowing them always basically grantees that we include the important points. Also we can test this way how people are willing to do stupid decisions that costs a lot and don't offer any benefits.

**Comment by Highlife1911** [comment]
Also add force deals. These are deals with property the system owns.

**Comment by ratnim** [comment]
Did not get what you mean by "force deals".

**Comment by ratnim** [comment]
When should the deals invoke? 
Event driven? 
Roll the dice
Event Cards
Build houses
Pay rents
buy streets

**Comment by ratnim** [comment]
Komponente sollte wissen wann sie welche Deals anbietet.  Wenn es einen großen teil des Spiels besitzt sollte es diese wieder gegen externe Inhalte eintauschen. Externe Inhalte sollten persistiert werden.

**Comment by ratnim** [comment]
Technisch könnte die Komponente das Spiel beobachten und darauf reagieren oder ein Teil des Spiels sein. Ich würde sagen das sie von außen agiert, da sich so auch eine Anwendung auf andere Spiele/Systeme möglich wäre.

**Comment by Highlife1911** [comment]
Forced deals are deals the player can not cancel because they include property that is owned by the system. Forced deals would allow interaction with the system by offering a bad deal to someone with additional reals world information. So if the system owns a color and I want to buy it, i can do this by betting a small amount of money and some private information. 

It is still unclear how should I know this because it is not visible to me.

**Comment by MarieTheresThomas** [comment]
• Selfaware Komponente
        ◦ Ziel: Spieler soll dazu incentiviert werden, maximal viele Informationen an das Spiel preiszugeben
        ◦ regelbasiert
            ▪ Ranking der Deals nach 
                • dahinterstehender Geldwert
                • Weltrelevanz
                • temporär oder langfristige Wirkung 
                • Belohnung für wiederholte Interaktion mit Selfaware Komponente durch wiederholte interaktion mit System 
            ▪ Progressive Anfragen basierend auf bestehenden Infos, 
                • Auswertung der vorhandenen Infos: 
                    ◦ Bsp: Facebook-Infos/Amazon Account auswerten, auf basis der neugefundenen Informaionen neue Deals anbieten
        ◦ Learning
            ▪ merkt sich infos
        ◦ zufällig
        ◦ zeitliche Begrenzung von
            ▪ Entscheidung des Spielers für Annahme des Deals
            ▪ Ausführung des Deals 
            ▪ idee: Zeitliche Überbrückung eines zeitlich länger andauernden Spielzuges eines Spielers durch proaktives Angebot eines Deals an die anderen Spieler, welchen diese innerhalb einer betsimmten Zeit annhemn können
        ◦ Ressourcen - ingame/extern
            ▪ Spiel fordert den Einsatz von externen Ressouren in Zusammenhang mit ingame- Spielaktionen 
                • Bsp: Dealangebot an Spieler: Unter Angabe von bestimmten Infos kostet das Häuserbauen die Hälfte des preises
            ▪ Trade off: entweder Einsatz von Ingame oder externen Ressourcen (informationen) 
        ◦ Belohnungssystem für Informationspreisgabe
            ▪ die Möglichkeit, Information an Spiel preiszugeben, besteht permanent
            ▪ freiwillige Informationspreisgbe wird innerhalb des Spielverlaufs belohnt

**Comment by ratnim** [comment]
Name: Watson
